### ISSUE TITLE
stylish2.0_edit don't support rich text mode

### ISSUE THREAD

**Issue by lychichem** [alice0775/userChrome.js#27]
For example, I like to write under rich text edit mode in stylish editor but find word in external editor, but when I do this, all the non-ascii charactors will change into unreadable codes after closing external editor. Would you please fix this issue? Thanks!

**Comment by Firef0x** [comment]
Bump! :up: I think it's a big problem to CJK users! Would you please fix it?

Yours sincerely! :bow:

**Comment by Firef0x** [comment]
@lychichem @alice0775 Sorry that I have solved the problem two months ago but forgot to open a pull request. Since I thought you probably gave up maintaining this script. :sweat_smile:
