### ISSUE TITLE
autoconfig loader for 72 distorts certain menupopups/menus

### ISSUE THREAD

**Issue by shmediaproductions** [alice0775/userChrome.js#54]
Basically the menuitems are supposed to be oriented in a vertical column, and they are for most menus. But certain menus (like the titlebar's Tools menu, or some menus in the bookmarks toolbar popup) are oriented in a weird row instead, stretching way beyond the bounds of the screen. I had this same thing happen a lot with the old "floating scrollbars" using xbl userchromeJS method, and then it was fixed when I switched to a newer agent sheet loader script that cut out everything non-essential. Anyway since I switched to the autoconfig loader for 72 it's come back, and I'm not really sure what's causing it since your userchrome.js script is so large. All I know is, [this is the script that caused the same problem back then](https://github.com/endeavoursc/firefox-overlay-scrollbars-win10/blob/master/userChrome.js), but I can't find any obvious similarities.

**Comment by alice0775** [comment]
This is basically Firefox's bug.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1589089 and https://bugzilla.mozilla.org/show_bug.cgi?id=1590280

**Comment by shmediaproductions** [comment]
By the way this bug seems to be fixed for me
